---
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: check-xml
      - id: check-json
      - id: check-yaml
  - repo: https://github.com/gitguardian/ggshield
    rev: v1.18.1
    hooks:
      - id: ggshield
        name: checking for secrets
        language_version: python3
        args: [ "-c", "ggshield.yaml", "secret", "scan", "pre-commit" ]
