kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-argocd-server
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-server
    namespace: sttrs-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-argocd-server
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-argocd-application-controller
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-application-controller
    namespace: sttrs-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-argocd-application-controller
---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: argocd-argocd-grafana
  namespace: demo
subjects:
  - kind: ServiceAccount
    name: argocd-argocd-grafana
    namespace: sttrs-argocd
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: argocd-argocd-grafana
