apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: broker-config-custom-resources-edit
  labels:
    rbac.authorization.k8s.io/aggregate-to-admin: "true"
    rbac.authorization.k8s.io/aggregate-to-edit: "true"
rules:
  - apiGroups: ["solace.broker.sbb.ch"]
    resources: ["*"]
    verbs: ["get", "list", "watch", "create",
            "update", "patch", "delete", "deletecollection"]
---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: broker-config-custom-resources-view
  labels:
    # Add these permissions to the "view" default role.
    rbac.authorization.k8s.io/aggregate-to-view: "true"
    rbac.authorization.k8s.io/aggregate-to-cluster-reader: "true"
rules:
  - apiGroups: ["solace.broker.sbb.ch"]
    resources: ["*"]
    verbs: ["get", "list", "watch"]


  CustomResourceDefinition